# Generated by Django 4.0.4 on 2022-06-21 23:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rich_specs',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
